server:
  port: 80
spring:
  datasource:
    hikari:
      maximum-pool-size: 50
  profiles:
    include: aggregator-api
logging:
  level:
    istu.bacs: trace
---

spring:
  profiles: cloud
  datasource:
    hikari:
      maximum-pool-size: 6