spring:
  profiles:
    include: aggregator-api,standings-updater
  datasource:
    hikari:
      maximum-pool-size: 20
logging:
  level:
    istu.bacs: DEBUG
---

spring:
  profiles: cloud
  datasource:
    hikari:
      maximum-pool-size: 3