spring:
  profiles:
    include: 'db,sybon-api,fake-api,standings-updater'
  datasource:
    hikari:
      maximum-pool-size: 20
logging:
  level:
    istu.bacs: TRACE
---

spring:
  profiles: cloud
  datasource:
    hikari:
      maximum-pool-size: 3