spring:
  profiles:
    include: aggregator-api,standings-updater
  datasource:
    hikari:
      maximum-pool-size: 3
logging:
  level:
    istu.bacs.background.combined: TRACE
    istu.bacs.standings: TRACE