server:
  port: 80
  tomcat:
    accept-count: 20000
spring:
  profiles:
    include: aggregator-api
  datasource:
    hikari:
      maximum-pool-size: 20
  jpa:
    open-in-view: false
logging:
  level:
    istu.bacs: DEBUG
---

spring:
  profiles: cloud
  datasource:
    hikari:
      maximum-pool-size: 6