server:
  port: 80
  tomcat:
    accept-count: 20000
spring:
  profiles:
    include: 'db,sybon-api,fake-api'
  datasource:
    hikari:
      maximum-pool-size: 20
logging:
  level:
    istu.bacs: DEBUG
---

spring:
  profiles: cloud
  datasource:
    hikari:
      maximum-pool-size: 6