spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/test_db
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none